development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mokotest
  pool: 5
  host: 127.0.0.1
  username: root
  password: 88888888
test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mokotest
  host: 127.0.0.1
  username: root
  password: 88888888

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: mokotest
  pool: 5
  host: 127.0.0.1
  username: root
  password: 88888888 
