Rails.application.routes.draw do
  
  get '/change_locale/:locale', to: 'settings#change_locale', as: :change_locale
  devise_for :users
  devise_for :admins, :skip => [:sessions]
  as :admin do
    get 'signin' => 'devise/sessions#new', :as => :new_admin_session
    post 'signin' => 'devise/sessions#create', :as => :admin_session
    delete 'signout' => 'devise/sessions#destroy', :as => :destroy_admin_session
  end
  #mount RailsAdmin::Engine => '/moko', as: 'rails_admin'
  #resources :work_flow

  match '/oauth/callback', to: 'oauth#callback', via: 'get'

  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/faq', to: 'static_pages#faq', via: 'get'
  match '/terms', to: 'static_pages#terms', via: 'get'
  match '/return', to: 'static_pages#returns', via: 'get'
  match '/shipping', to: 'static_pages#shipping', via: 'get'
  match '/supplier', to: 'static_pages#supplier', via: 'get'
  match '/payment', to: 'static_pages#payment', via: 'get'
  match '/privacy', to: 'static_pages#privacy', via: 'get'
  match '/technical', to: 'static_pages#technical', via: 'get'
  match '/how_to_use', to: 'static_pages#how', via: 'get'
  match '/search', to: 'boms#search_change', via: 'post'
  #get ':boms/:search_keyword/:mpn', to: 'boms#search_keyword'
  #get '/:search_keyword', to: 'boms#search_keyword'

  get 'boms/search_keyword/:mpn', to: 'boms#search_keyword'


  match '/down_excel', to: 'boms#down_excel', via: 'get'
  match '/show_excel', to: 'boms#show_excel', via: 'get'
  match '/work_flow', to: 'work_flow#index', via: 'post'  
  match '/work_flow', to: 'work_flow#index', via: 'get'  
  match '/up_work', to: 'work_flow#up_work', via: 'post'
  match '/edit_work_item', to: 'work_flow#edit_work_item', via: 'post'
  match '/edit_work_color', to: 'work_flow#edit_work_color', via: 'get'
  match '/edit_work', to: 'work_flow#edit_work', via: 'post'
  match '/edit_work', to: 'work_flow#edit_work', via: 'get'
  match '/up_warehouse', to: 'work_flow#up_warehouse', via: 'post'
  match '/order_state', to: 'work_flow#order_state', via: 'post'
  match '/feedback', to: 'work_flow#show', via: 'get'
  match '/add_feed', to: 'work_flow#add_feed', via: 'post'
  match '/indexup', to: 'work_flow#indexup', via: 'get' 
  match '/up_enddate', to: 'work_flow#up_enddate', via: 'post' 
  match '/sell_baojia', to: 'work_flow#sell_baojia', via: 'get'
  match '/sell_baojia_erp', to: 'work_flow#sell_baojia_erp', via: 'get'
  match '/edit_orderinfo', to: 'work_flow#edit_orderinfo', via: 'post'
  match '/edit_orderinfo_erp', to: 'work_flow#edit_orderinfo_erp', via: 'post'
  match '/sell_view_baojia', to: 'work_flow#sell_view_baojia', via: 'get'
  match '/moko_part_manage', to: 'work_flow#moko_part_manage', via: 'get'
  match '/moko_part_update', to: 'work_flow#moko_part_update', via: 'post'
  match '/sell_pcb_baojia', to: 'work_flow#sell_pcb_baojia', via: 'get'
  match '/add_pcb_customer', to: 'work_flow#add_pcb_customer', via: 'post'
  match '/edit_pcb_customer', to: 'work_flow#edit_pcb_customer', via: 'post'
  match '/pcb_order_list', to: 'work_flow#pcb_order_list', via: 'get'
  match '/new_pcb_order', to: 'work_flow#new_pcb_order', via: 'get'
  match '/add_pcb_order_item', to: 'work_flow#add_pcb_order_item', via: 'post'
  match '/edit_pcb_order_item', to: 'work_flow#edit_pcb_order_item', via: 'post'
  match '/edit_pcb_order', to: 'work_flow#edit_pcb_order', via: 'post'
  match '/work_flow/select_pcbcustomer_ajax', to: 'work_flow#select_pcbcustomer_ajax', via: 'get'
  match '/update_pcb_price', to: 'work_flow#update_pcb_price', via: 'post'
  match '/release_pcb_to_order', to: 'work_flow#release_pcb_to_order', via: 'post'
  match '/release_pcb_to_quote', to: 'work_flow#release_pcb_to_quote', via: 'get'
  match '/release_pcb_to_quotechk', to: 'work_flow#release_pcb_to_quotechk', via: 'get'
  match '/follow', to: 'work_flow#follow', via: 'get'
  match '/find_c', to: 'work_flow#find_c', via: 'get'
  match '/find_c_pi', to: 'work_flow#find_c_pi', via: 'get'
  match '/del_pcb_order', to: 'work_flow#del_pcb_order', via: 'get'
  match '/back_pcb_to_order', to: 'work_flow#back_pcb_to_order', via: 'get'
  match '/del_pcb_follow', to: 'work_flow#del_pcb_follow', via: 'get'
  match '/find_c_ch', to: 'work_flow#find_c_ch', via: 'get'
  match '/find_c_pi_ch', to: 'work_flow#find_c_pi_ch', via: 'get'
  match '/new_pcb_pi', to: 'work_flow#new_pcb_pi', via: 'get'
  match '/edit_pcb_pi', to: 'work_flow#edit_pcb_pi', via: 'get'
  match '/find_order', to: 'work_flow#find_order', via: 'get'
  match '/find_order_check', to: 'work_flow#find_order_check', via: 'get'
  match '/pi_draft', to: 'work_flow#pi_draft', via: 'post'
  match '/pi_draft_list', to: 'work_flow#pi_draft_list', via: 'get'
  match '/pi_save', to: 'work_flow#pi_save', via: 'get'
  match '/sell_baojia_q', to: 'work_flow#sell_baojia_q', via: 'get'
  match '/unfollow_bom_item', to: 'work_flow#unfollow_bom_item', via: 'get'
  match '/unfollow_bom_item_more', to: 'work_flow#unfollow_bom_item_more', via: 'post'
  match '/find_moko_part', to: 'work_flow#find_moko_part', via: 'get'
  match '/edit_pcb_order', to: 'work_flow#edit_pcb_order', via: 'get'
  match '/find_moko_part_ch', to: 'work_flow#find_moko_part_ch', via: 'get'
  match '/del_pcb_order_item', to: 'work_flow#del_pcb_order_item', via: 'get'
  match '/update_pcb_order', to: 'work_flow#update_pcb_order', via: 'post'
  match '/del_pi_item', to: 'work_flow#del_pi_item', via: 'get'
  match '/del_pcb_pi', to: 'work_flow#del_pcb_pi', via: 'get'
  match '/edit_pi_item', to: 'work_flow#edit_pi_item', via: 'post'
  match '/add_pcb_order_sell_item', to: 'work_flow#add_pcb_order_sell_item', via: 'post'
  match '/edit_pcb_order_sell_item', to: 'work_flow#edit_pcb_order_sell_item', via: 'post'
  match '/del_pcb_order_sell_item', to: 'work_flow#del_pcb_order_sell_item', via: 'get'
  match '/copy_order_item', to: 'work_flow#copy_order_item', via: 'get'
  match '/bom_edit_order_item', to: 'work_flow#bom_edit_order_item', via: 'post'
  match '/add_pi_other_item', to: 'work_flow#add_pi_other_item', via: 'post'
  match '/edit_pi_other_item', to: 'work_flow#edit_pi_other_item', via: 'post'
  match '/del_pi_other_item', to: 'work_flow#del_pi_other_item', via: 'get'
  match '/pi_list', to: 'work_flow#pi_list', via: 'get'
  match '/pi_buy_list', to: 'work_flow#pi_buy_list', via: 'get'
  match '/new_pi_buy', to: 'work_flow#new_pi_buy', via: 'get'
  match '/edit_pi_buy', to: 'work_flow#edit_pi_buy', via: 'get'
  match '/find_dn', to: 'work_flow#find_dn', via: 'get'
  match '/find_dn_ch', to: 'work_flow#find_dn_ch', via: 'get'
  match '/find_pi_buy', to: 'work_flow#find_pi_buy', via: 'get'
  match '/add_pi_buy_item', to: 'work_flow#add_pi_buy_item', via: 'get'
  match '/pi_waitfor_buy', to: 'work_flow#pi_waitfor_buy', via: 'get'
  match '/send_pi_buy', to: 'work_flow#send_pi_buy', via: 'post'
  match '/pi_buy_history', to: 'work_flow#pi_buy_history', via: 'get'
  match '/pi_buy_item', to: 'work_flow#pi_buy_item', via: 'get'
  match '/p_wh_in', to: 'work_flow#p_wh_in', via: 'post'
  match '/wh_in', to: 'work_flow#wh_in', via: 'get'
  match '/wh_out', to: 'work_flow#wh_out', via: 'get'
  match '/wh_query', to: 'work_flow#wh_query', via: 'get'
  match '/wh_find', to: 'work_flow#wh_find', via: 'get'
  match '/wh_draft_list', to: 'work_flow#wh_draft_list', via: 'get'
  match '/edit_wh_order', to: 'work_flow#edit_wh_order', via: 'get'
  match '/new_wh_order', to: 'work_flow#new_wh_order', via: 'get'
  match '/find_w_wh', to: 'work_flow#find_w_wh', via: 'get'
  match '/find_w_chanpin', to: 'work_flow#find_w_chanpin', via: 'get'
  match '/add_wh_item', to: 'work_flow#add_wh_item', via: 'post'
  match '/add_wh_item_chengpin', to: 'work_flow#add_wh_item_chengpin', via: 'post'
  match '/del_wh_item', to: 'work_flow#del_wh_item', via: 'get'
  match '/wh_draft', to: 'work_flow#wh_draft', via: 'post'
  match '/del_wh', to: 'work_flow#del_wh', via: 'get'
  match '/pi_print', to: 'work_flow#pi_print', via: 'get'
  match '/add_pi_sb', to: 'work_flow#add_pi_sb', via: 'post'
  match '/edit_user_info', to: 'work_flow#edit_user_info', via: 'post'
  match '/edit_c_info', to: 'work_flow#edit_c_info', via: 'post'
  match '/pi_out_excel', to: 'work_flow#pi_out_excel', via: 'get'
  match '/pi_out_xlsx_moko_a', to: 'work_flow#pi_out_xlsx_moko_a', via: 'get'
  match '/pi_out_xlsx_moko_b', to: 'work_flow#pi_out_xlsx_moko_b', via: 'get'
  match '/pi_out_xlsx_moko_c', to: 'work_flow#pi_out_xlsx_moko_c', via: 'get'
  match '/pi_out_xlsx_moko_d', to: 'work_flow#pi_out_xlsx_moko_d', via: 'get'
  match '/find_linkbom', to: 'work_flow#find_linkbom', via: 'get'
  match '/find_linkbom_moko', to: 'work_flow#find_linkbom_moko', via: 'get'
  match '/find_linkbom_link', to: 'work_flow#find_linkbom_link', via: 'get'
  match '/new_moko_part', to: 'work_flow#new_moko_part', via: 'get'
  match '/new_moko_part', to: 'work_flow#new_moko_part', via: 'post'
  match '/add_part_moko', to: 'work_flow#add_part_moko', via: 'post'
  match '/add_new_moko_part', to: 'work_flow#add_new_moko_part', via: 'post'
  match '/pmc_h', to: 'work_flow#pmc_h', via: 'get'
  match '/pmc_new', to: 'work_flow#pmc_new', via: 'get'
  match '/pmc_wh_check_apply_for_list', to: 'work_flow#pmc_wh_check_apply_for_list', via: 'get'
  match '/pmc_wh_check_apply_for', to: 'work_flow#pmc_wh_check_apply_for', via: 'post'
  match '/pmc_wh_check_list', to: 'work_flow#pmc_wh_check_list', via: 'get'
  match '/pmc_wh_check_pass', to: 'work_flow#pmc_wh_check_pass', via: 'post'
  match '/del_pmc_wh_check_pass', to: 'work_flow#del_pmc_wh_check_pass', via: 'get'
  match '/pmc_check_pass', to: 'work_flow#pmc_check_pass', via: 'get'
  match '/del_pmc_wh_check_pass', to: 'work_flow#del_pmc_wh_check_pass', via: 'get'
  match '/cost_history_buy', to: 'work_flow#cost_history_buy', via: 'get'
  match '/del_pi_buy_item', to: 'work_flow#del_pi_buy_item', via: 'get'
  match '/edit_pi_buy_qty_cost', to: 'work_flow#edit_pi_buy_qty_cost', via: 'post'
  match '/pi_buy_check_list', to: 'work_flow#pi_buy_check_list', via: 'get'
  match '/pi_buy_checked_list', to: 'work_flow#pi_buy_checked_list', via: 'get'
  match '/send_pi_buy_check', to: 'work_flow#send_pi_buy_check', via: 'post'
  match '/send_pi_buy_check', to: 'work_flow#send_pi_buy_check', via: 'get'
  match '/factory_in', to: 'work_flow#factory_in', via: 'get'
  match '/factory_out', to: 'work_flow#factory_out', via: 'get'
  match '/wh_material_flow', to: 'work_flow#wh_material_flow', via: 'get'
  match '/wh_draft_change_list', to: 'work_flow#wh_draft_change_list', via: 'get'
  match '/new_wh_change_order', to: 'work_flow#new_wh_change_order', via: 'get'
  match '/edit_wh_change_order', to: 'work_flow#edit_wh_change_order', via: 'get'
  match '/del_wh_change', to: 'work_flow#del_wh_change', via: 'get'
  match '/find_w_wh_change', to: 'work_flow#find_w_wh_change', via: 'get'
  match '/add_wh_change_item', to: 'work_flow#add_wh_change_item', via: 'post'
  match '/wh_draft_change', to: 'work_flow#wh_draft_change', via: 'post'
  match '/factory_online', to: 'work_flow#factory_online', via: 'get'
  match '/pmc_check_pass_all', to: 'work_flow#pmc_check_pass_all', via: 'post'
  match '/edit_buy_user', to: 'work_flow#edit_buy_user', via: 'post'
  match '/pmc_add_list', to: 'work_flow#pmc_add_list', via: 'get'
  match '/new_pmc_add_order', to: 'work_flow#new_pmc_add_order', via: 'get'
  match '/edit_pmc_add_order', to: 'work_flow#edit_pmc_add_order', via: 'get'
  match '/add_pmc_add_item', to: 'work_flow#add_pmc_add_item', via: 'post'
  match '/del_add_pmc_add_item', to: 'work_flow#del_add_pmc_add_item', via: 'get'
  match '/send_to_pi_pmc_item', to: 'work_flow#send_to_pi_pmc_item', via: 'post'
  match '/edit_pmc_add_buy_user', to: 'work_flow#edit_pmc_add_buy_user', via: 'post'
  match '/send_pi_buy_checked', to: 'work_flow#send_pi_buy_checked', via: 'post'
  match '/new_moko_supplier', to: 'work_flow#new_moko_supplier', via: 'post'
  match '/edit_moko_supplier', to: 'work_flow#edit_moko_supplier', via: 'post'
  match '/moko_supplier_list', to: 'work_flow#moko_supplier_list', via: 'get'
  match '/pi_draft', to: 'work_flow#pi_draft', via: 'get'
  match '/pi_to_pmc', to: 'work_flow#pi_to_pmc', via: 'post'
  match '/new_payment_notice', to: 'work_flow#new_payment_notice', via: 'post'
  match '/payment_notice_list', to: 'work_flow#payment_notice_list', via: 'get'
  match '/sell_payment_notice_list', to: 'work_flow#sell_payment_notice_list', via: 'get'
  match '/new_voucher', to: 'work_flow#new_voucher', via: 'post'
  match '/edit_voucher', to: 'work_flow#edit_voucher', via: 'post'
  match '/edit_payment_notice', to: 'work_flow#edit_payment_notice', via: 'post'
  match '/payment_voucher_list', to: 'work_flow#payment_voucher_list', via: 'get'
  match '/setup_finance', to: 'work_flow#setup_finance', via: 'get'
  match '/edit_setup_finance', to: 'work_flow#edit_setup_finance', via: 'post'
  match '/fu_kuan_shen_qing_list', to: 'work_flow#fu_kuan_shen_qing_list', via: 'get'



  match '/edit_fu_kuan_shen_qing_dan', to: 'work_flow#edit_fu_kuan_shen_qing_dan', via: 'get'
  match '/add_fu_kuan_shen_qing_dan_item', to: 'work_flow#add_fu_kuan_shen_qing_dan_item', via: 'get'
  match '/edit_zhi_fu_bi_li', to: 'work_flow#edit_zhi_fu_bi_li', via: 'post'
  match '/edit_fu_kuan_remark', to: 'work_flow#edit_fu_kuan_remark', via: 'post'
  match '/fu_kuan_shen_qing_to_check', to: 'work_flow#fu_kuan_shen_qing_to_check', via: 'post'
  match '/fu_kuan_shen_qing_to_checked', to: 'work_flow#fu_kuan_shen_qing_to_checked', via: 'post'
  match '/fu_kuan_dan_list', to: 'work_flow#fu_kuan_dan_list', via: 'get'
  match '/new_fu_kuan_dan', to: 'work_flow#new_fu_kuan_dan', via: 'get'
  match '/edit_fu_kuan_dan', to: 'work_flow#edit_fu_kuan_dan', via: 'get'
  match '/edit_fu_kuan_p', to: 'work_flow#edit_fu_kuan_p', via: 'post'
  match '/edit_fukuandan_finance_at', to: 'work_flow#edit_fukuandan_finance_at', via: 'post'
  match '/edit_fukuandan_xianjin_kemu', to: 'work_flow#edit_fukuandan_xianjin_kemu', via: 'post'
  match '/fu_kuan_dan_to_check', to: 'work_flow#fu_kuan_dan_to_check', via: 'post'
  match '/fu_kuan_dan_to_checked', to: 'work_flow#fu_kuan_dan_to_checked', via: 'post'
  match '/find_fu_kuan_item', to: 'work_flow#find_fu_kuan_item', via: 'post'
  match '/cai_gou_fa_piao_list', to: 'work_flow#cai_gou_fa_piao_list', via: 'get'
  match '/edit_cai_gou_fa_piao', to: 'work_flow#edit_cai_gou_fa_piao', via: 'post'
  match '/show_cai_gou_fa_piao', to: 'work_flow#show_cai_gou_fa_piao', via: 'get'
  match '/factory_in_manual', to: 'work_flow#factory_in_manual', via: 'get'
  match '/factory_online_manual', to: 'work_flow#factory_online_manual', via: 'get'
  match '/edit_ling_liao_dan', to: 'work_flow#edit_ling_liao_dan', via: 'get'
  match '/check_ling_liao_dan', to: 'work_flow#check_ling_liao_dan', via: 'post'
  match '/up_ling_liao_dan', to: 'work_flow#up_ling_liao_dan', via: 'post'
  match '/edit_ling_liao_item_qty', to: 'work_flow#edit_ling_liao_item_qty', via: 'post'
  match '/add_ling_liao_dan_item', to: 'work_flow#add_ling_liao_dan_item', via: 'post'
  match '/edit_pi_bank_info', to: 'work_flow#edit_pi_bank_info', via: 'post'
  match '/edit_pi_info_t_p', to: 'work_flow#edit_pi_info_t_p', via: 'post'
  match '/send_pmc_back', to: 'work_flow#send_pmc_back', via: 'get'
  match '/pmc_to_sell', to: 'work_flow#pmc_to_sell', via: 'get'
  match '/pmc_back_to_pi', to: 'work_flow#pmc_back_to_pi', via: 'get'
  match '/sell_back_item', to: 'work_flow#sell_back_item', via: 'get'
  match '/ecn_list', to: 'work_flow#ecn_list', via: 'get'
  match '/edit_wh_order_songhuono', to: 'work_flow#edit_wh_order_songhuono', via: 'post'
  match '/edit_wh_order_remark', to: 'work_flow#edit_wh_order_remark', via: 'post'
  match '/edit_fu_kuan_bank_user', to: 'work_flow#edit_fu_kuan_bank_user', via: 'post'
  match '/new_ecn', to: 'work_flow#new_ecn', via: 'get'
  match '/new_ecn_find_pi', to: 'work_flow#new_ecn_find_pi', via: 'get'
  match '/edit_ecn', to: 'work_flow#edit_ecn', via: 'get'
  match '/add_ecn', to: 'work_flow#add_ecn', via: 'post'
  match '/add_ecn_item', to: 'work_flow#add_ecn_item', via: 'post'
  match '/up_ecn_item', to: 'work_flow#up_ecn_item', via: 'post'
  match '/edit_ecn_up', to: 'work_flow#edit_ecn_up', via: 'post'
  match '/edit_j_h_r_q', to: 'work_flow#edit_j_h_r_q', via: 'post'
  match '/edit_fu_kuan_bank', to: 'work_flow#edit_fu_kuan_bank', via: 'post'
  match '/edit_fu_kuan_info_a', to: 'work_flow#edit_fu_kuan_info_a', via: 'post'
  match '/edit_fu_kuan_info_b', to: 'work_flow#edit_fu_kuan_info_b', via: 'post'
  match '/clean_work_date_smd', to: 'work_flow#clean_work_date_smd', via: 'get'
  match '/clean_work_date_dip', to: 'work_flow#clean_work_date_dip', via: 'get'
  match '/cut_in_ecn', to: 'work_flow#cut_in_ecn', via: 'post'
  match '/voucher_checked', to: 'work_flow#voucher_checked', via: 'get'
  match '/voucher_uncheck', to: 'work_flow#voucher_uncheck', via: 'get'
  match '/shou_kuan_ping_zheng', to: 'work_flow#shou_kuan_ping_zheng', via: 'get'
  match '/fu_kuan_ping_zheng', to: 'work_flow#fu_kuan_ping_zheng', via: 'get'
  match '/zong_zhang_list', to: 'work_flow#zong_zhang_list', via: 'get'
  match '/zong_zhang_new_list', to: 'work_flow#zong_zhang_new_list', via: 'get'
  match '/edit_ping_zheng_up', to: 'work_flow#edit_ping_zheng_up', via: 'post'
  match '/edit_ping_zheng', to: 'work_flow#edit_ping_zheng', via: 'get'
  match '/new_ping_zheng', to: 'work_flow#new_ping_zheng', via: 'post'
  match '/ping_zheng_new', to: 'work_flow#ping_zheng_new', via: 'get'
  match '/ping_zheng_del', to: 'work_flow#ping_zheng_del', via: 'get'
  match '/work_flow_merchandiser', to: 'work_flow#work_flow_merchandiser', via: 'get'
  match '/find_pmc_pi', to: 'work_flow#find_pmc_pi', via: 'post'
  match '/set_pmc_pi', to: 'work_flow#set_pmc_pi', via: 'get'
  match '/manual_pmc_item', to: 'work_flow#manual_pmc_item', via: 'post'
  match '/pmc_close', to: 'work_flow#pmc_close', via: 'get'
  match '/edit_pmc_remark', to: 'work_flow#edit_pmc_remark', via: 'post'
  match '/wh_get', to: 'work_flow#wh_get', via: 'get'
  match '/new_wh_get', to: 'work_flow#new_wh_get', via: 'get'
  match '/edit_wh_get', to: 'work_flow#edit_wh_get', via: 'get'
  match '/find_wh_get_bom', to: 'work_flow#find_wh_get_bom', via: 'post'
  match '/wh_get_bom_up', to: 'work_flow#wh_get_bom_up', via: 'get'
  match '/edit_wh_item_qty', to: 'work_flow#edit_wh_item_qty', via: 'post'
  match '/wh_get_to_check', to: 'work_flow#wh_get_to_check', via: 'post'
  match '/wh_out', to: 'work_flow#wh_out', via: 'get'
  match '/new_wh_out', to: 'work_flow#new_wh_out', via: 'get'
  match '/edit_wh_out', to: 'work_flow#edit_wh_out', via: 'get'
  match '/find_wh_out', to: 'work_flow#find_wh_out', via: 'post'
  match '/wh_out_item_up', to: 'work_flow#wh_out_item_up', via: 'get'
  match '/wh_out_to_check', to: 'work_flow#wh_out_to_check', via: 'post'
  match '/edit_buy_qty', to: 'work_flow#edit_buy_qty', via: 'post'
  match '/pmc_list', to: 'work_flow#pmc_list', via: 'get'
  match '/send_pi_buy_checked_item', to: 'work_flow#send_pi_buy_checked_item', via: 'get'
  match '/fu_kuan_shen_qing_type', to: 'work_flow#fu_kuan_shen_qing_type', via: 'post'
  match '/edit_fu_kuan_shen_qing_type', to: 'work_flow#edit_fu_kuan_shen_qing_type', via: 'post'
  match '/new_fu_kuan_shen_qing_dan', to: 'work_flow#new_fu_kuan_shen_qing_dan', via: 'get'
  match '/edit_new_fu_kuan_shen_qing_dan', to: 'work_flow#edit_new_fu_kuan_shen_qing_dan', via: 'get'
  match '/find_supplier', to: 'work_flow#find_supplier', via: 'post'
  match '/edit_find_supplier', to: 'work_flow#edit_find_supplier', via: 'post'
  match '/edit_pi_buy_remark', to: 'work_flow#edit_pi_buy_remark', via: 'post'







  match '/procurement_new', to: 'procurement#p_create_bom', via: 'get' 
  match '/p_new_bom', to: 'procurement#p_upbom',via: 'post'
  match '/p_new_bom', to: 'procurement#p_upbom',via: 'get'
  match '/p_select_column', to: 'procurement#p_select_column',via: 'get' 
  match '/p_search_part', to: 'procurement#p_search_part',via: 'post'
  match '/p_viewbom', to: 'procurement#p_viewbom',via: 'get'
  match '/moko_view_bom', to: 'procurement#moko_view_bom',via: 'get'
  match '/moko_bom_upgrade', to: 'procurement#moko_bom_upgrade',via: 'post'
  match '/moko_bom_up_done', to: 'procurement#moko_bom_up_done',via: 'post'
  match '/p_viewbom', to: 'procurement#p_viewbom',via: 'post'
  match '/p_update_bom', to: 'procurement#update_bom',via: 'post'
  match '/p_get_bom', to: 'procurement#p_get_bom',via: 'get'
  match '/p_del_bom', to: 'procurement#p_del_bom',via: 'post'
  match '/p_add_bom', to: 'procurement#p_add_bom',via: 'post'
  match '/p_bomlist', to: 'procurement#p_bomlist',via: 'get'
  match '/moko_bom_list', to: 'procurement#moko_bom_list', via: 'get'
  match '/search_m', to: 'procurement#search_m',via: 'post'
  match '/search_m', to: 'procurement#search_m',via: 'get'
  match '/search_m_ecn', to: 'procurement#search_m_ecn',via: 'post'
  match '/search_m_ecn', to: 'procurement#search_m_ecn',via: 'get'
  match '/set_ecn', to: 'procurement#set_ecn',via: 'get'

  match '/search_m_moko', to: 'procurement#search_m_moko',via: 'post'
  match '/search_m_moko', to: 'procurement#search_m_moko',via: 'get'
  match '/p_update', to: 'procurement#p_update',via: 'get'
  match '/p_update_moko', to: 'procurement#p_update_moko',via: 'get'
  match '/p_updateii', to: 'procurement#p_updateii',via: 'get'
  match '/p_edit', to: 'procurement#p_edit',via: 'post'
  match '/p_edit', to: 'procurement#p_edit',via: 'get'
  match '/p_up_userdo', to: 'procurement#p_up_userdo',via: 'get'
  match '/del_dn', to: 'procurement#del_dn',via: 'get'
  match '/p_edit_dn', to: 'procurement#p_edit_dn',via: 'post'
  match '/up_check', to: 'procurement#up_check',via: 'post'
  match '/p_excel_m', to: 'procurement#p_excel_m',via: 'get'
  match '/p_excel', to: 'procurement#p_excel',via: 'get'
  match '/p_excel_part_list', to: 'procurement#p_excel_part_list',via: 'post'
  match '/p_profit', to: 'procurement#p_profit',via: 'post'
  match '/del_cost', to: 'procurement#del_cost',via: 'get'
  match '/up_check', to: 'procurement#up_check',via: 'get'
  match '/p_edit_mpn', to: 'procurement#p_edit_mpn',via: 'post'
  match '/p_edit_mpn_moko', to: 'procurement#p_edit_mpn_moko',via: 'post'
  match '/copy_data', to: 'procurement#copy_data',via: 'get'
  match '/p_del_bb', to: 'procurement#p_del_bb',via: 'get'
  match '/procurement/select_with_ajax', to: 'procurement#select_with_ajax', via: 'post'
  match '/procurement/select_with_ajax', to: 'procurement#select_with_ajax', via: 'get'
  match '/add_moko_part', to: 'procurement#add_moko_part', via: 'get'
  match '/add_moko_part', to: 'procurement#add_moko_part', via: 'post'
  match '/pj_edit', to: 'procurement#pj_edit', via: 'post'
  match '/add_order', to: 'procurement#add_order', via: 'get'
  match '/p_history', to: 'procurement#p_history', via: 'get'
  match '/p_edit_cost_dn', to: 'procurement#p_edit_cost_dn', via: 'post'
  match '/p_edit_supplier_dn', to: 'procurement#p_edit_supplier_dn', via: 'post'
  match '/supplier_offer', to: 'procurement#supplier_offer', via: 'get'
  match '/supplier_dn_excel', to: 'procurement#supplier_dn_excel', via: 'get'
  match '/part_list', to: 'procurement#part_list', via: 'get'
  match '/send_order_to_p', to: 'procurement#send_order_to_p', via: 'get'
  match '/remark_to_sell', to: 'procurement#remark_to_sell', via: 'get'
  match '/p_item_remark', to: 'procurement#p_item_remark', via: 'post'
  match '/p_item_remark_up', to: 'procurement#p_item_remark_up', via: 'post'
  match '/p_item_remark_del', to: 'procurement#p_item_remark_del', via: 'get'
  match '/p_excel_add', to: 'procurement#p_excel_add', via: 'get'
  match '/supplier_d_list', to: 'procurement#supplier_d_list', via: 'get'
  match '/add_sd', to: 'procurement#add_sd', via: 'post'
  match '/update_sd', to: 'procurement#update_sd', via: 'post'
  match '/find_sd', to: 'procurement#find_sd', via: 'get'
  match '/sd_flow', to: 'procurement#sd_flow', via: 'get'
  match '/sd_back', to: 'procurement#sd_back', via: 'get'
  match '/update_p_data', to: 'procurement#update_p_data', via: 'get'
  match '/other_baojia', to: 'procurement#other_baojia', via: 'get'
  match '/other_baojia_out', to: 'procurement#other_baojia_out', via: 'get'
  match '/other_baojia_clean', to: 'procurement#other_baojia_clean', via: 'get'
  match '/other_baojia_up', to: 'procurement#other_baojia_up', via: 'get'
  match '/other_baojia_up', to: 'procurement#other_baojia_up', via: 'post'
  match '/moko_part_data', to: 'procurement#moko_part_data', via: 'get'
  match '/add_dn', to: 'procurement#add_dn', via: 'post'
  match '/com_part_list', to: 'procurement#com_part_list', via: 'get'
  match '/edit_com_price', to: 'procurement#edit_com_price', via: 'post'
  match '/pcb_list', to: 'procurement#pcb_list', via: 'get'
  match '/pcb_info_update', to: 'procurement#pcb_info_update', via: 'post'
  match '/bom_v_up', to: 'procurement#bom_v_up', via: 'post'
  match '/bom_v_up_moko', to: 'procurement#bom_v_up_moko', via: 'post'
  match '/copy_pcb_item_info', to: 'procurement#copy_pcb_item_info', via: 'get'
  match '/cost_history', to: 'procurement#cost_history', via: 'get'
  match '/sell_feeback_list', to: 'procurement#sell_feeback_list', via: 'get'
  match '/edit_item_qty', to: 'procurement#edit_item_qty', via: 'post'
  match '/del_bom_item', to: 'procurement#del_bom_item', via: 'get'
  match '/edit_item_ref', to: 'procurement#edit_item_ref', via: 'post'
  match '/del_bom_item_moko', to: 'procurement#del_bom_item_moko', via: 'get'
  match '/edit_item_ref_moko', to: 'procurement#edit_item_ref_moko', via: 'post'
  match '/pcb_list_del', to: 'procurement#pcb_list_del', via: 'get'
  match '/chk_add_bom_item', to: 'procurement#chk_add_bom_item', via: 'get'
  match '/jia_ji', to: 'procurement#jia_ji', via: 'get'
  match '/fan_jia_ji', to: 'procurement#fan_jia_ji', via: 'get'
  match '/up_all_dn', to: 'procurement#up_all_dn', via: 'get'





#external_bom
  match '/e_new', to: 'external_bom#p_create_bom', via: 'get' 
  match '/e_new_bom', to: 'external_bom#p_upbom',via: 'post'
  match '/e_new_bom', to: 'external_bom#p_upbom',via: 'get'
  match '/e_select_column', to: 'external_bom#p_select_column',via: 'get' 
  match '/e_search_part', to: 'external_bom#p_search_part',via: 'post'
  match '/e_viewbom', to: 'external_bom#p_viewbom',via: 'get'
  match '/e_viewbom', to: 'external_bom#p_viewbom',via: 'post'
  match '/e_update_bom', to: 'external_bom#update_bom',via: 'post'
  match '/e_get_bom', to: 'external_bom#p_get_bom',via: 'get'
  match '/e_del_bom', to: 'external_bom#p_del_bom',via: 'post'
  match '/e_add_bom', to: 'external_bom#p_add_bom',via: 'post'
  match '/e_bomlist', to: 'external_bom#p_bomlist',via: 'get'
  match '/e_search_m', to: 'external_bom#search_m',via: 'post'
  match '/e_search_m', to: 'external_bom#search_m',via: 'get'
  match '/e_update', to: 'external_bom#p_update',via: 'get'
  match '/e_updateii', to: 'external_bom#p_updateii',via: 'get'
  match '/e_edit', to: 'external_bom#p_edit',via: 'post'
  #match '/e_edit', to: 'external_bom#p_edit',via: 'get'
  match '/e_up_userdo', to: 'external_bom#p_up_userdo',via: 'get'
  match '/e_del_dn', to: 'external_bom#del_dn',via: 'get'
  match '/e_edit_dn', to: 'external_bom#p_edit_dn',via: 'post'
  match '/e_up_check', to: 'external_bom#up_check',via: 'post'
  match '/e_excel', to: 'external_bom#p_excel',via: 'get'
  match '/e_profit', to: 'external_bom#p_profit',via: 'post'
  match '/e_del_cost', to: 'external_bom#del_cost',via: 'get'
  match '/e_up_check', to: 'external_bom#up_check',via: 'get'
  match '/e_edit_mpn', to: 'external_bom#p_edit_mpn',via: 'post'
  match '/e_copy_data', to: 'external_bom#copy_data',via: 'get'
  match '/e_del_bb', to: 'external_bom#p_del_bb',via: 'get'




  match '/timesheet', to: 'timesheet#index', via: 'post'  
  match '/timesheet', to: 'timesheet#index', via: 'get' 
  match '/up_timesheet', to: 'timesheet#up_timesheet', via: 'post'  
  match '/down_timesheet', to: 'timesheet#down_excel', via: 'post'

  match '/mpn_info', to: 'mpn_info#index', via: 'get' 
  match '/up_mpn', to: 'mpn_info#up_mpn', via: 'post' 
  match '/down_mpn_excel', to: 'mpn_info#down_excel', via: 'get'

  root to: 'boms#root'
  #root to: "boms#index"
  match '/new_bom', to: 'boms#upbom',via: 'post'
  match '/new_bom', to: 'boms#upbom',via: 'get'
  match '/boms/choose', to: 'boms#choose',via: 'get'
  #match '/boms', to: 'boms#index',via: 'get'
  match '/boms/search_api', to: 'boms#search_api',via: 'post'
  match '/bom_item/edit', to: 'bom_item#edit', via: 'post'
  match '/boms/mpn', to: 'boms#mpn#', via: 'get'
  match '/mpn_item', to: 'boms#mpn_item', via: 'get'
  match '/des_item', to: 'boms#des_item', via: 'get'
  match '/search_part', to: 'boms#search_part',via: 'post'
  match '/viewbom', to: 'boms#viewbom',via: 'get'
  match '/viewbom', to: 'boms#viewbom',via: 'post'
  match '/vieworder', to: 'boms#vieworder',via: 'get'
  match '/bomlist', to: 'boms#bomlist',via: 'get'
  match '/up_order_info', to: 'boms#up_order_info',via: 'post'
  match '/up_order_info', to: 'boms#up_order_info',via: 'get'
  match '/up_pcb_info', to: 'boms#up_pcb_info',via: 'get'
  match '/up_pcb_info', to: 'boms#up_pcb_info',via: 'post'
  match '/create_order', to: 'boms#create_order',via: 'post'
  match '/orderlist', to: 'boms#orderlist',via: 'post'
  match '/orderlist', to: 'boms#orderlist',via: 'get'
  match '/order_review_list', to: 'boms#order_review_list',via: 'get'
  match '/order_review', to: 'boms#order_review',via: 'get'
  match '/review_pass', to: 'boms#review_pass',via: 'post'
  match '/order_dc_list', to: 'boms#order_dc_list',via: 'get'
  match '/order_dc', to: 'boms#order_dc',via: 'get'
  match '/dc_pass', to: 'boms#dc_pass',via: 'post' 
  match '/pcb_dc_change', to: 'boms#pcb_dc_change',via: 'post' 
  match '/pcb_r_change', to: 'boms#pcb_r_change',via: 'post' 
  match '/select_column', to: 'boms#select_column',via: 'get' 
  match '/user_profile', to: 'boms#user_profile',via: 'get' 
  match '/up_user_profile', to: 'boms#up_user_profile',via: 'post' 
  match '/edit_billing', to: 'boms#edit_billing',via: 'post' 
  match '/edit_shipping', to: 'boms#edit_shipping',via: 'post'
  match '/del_billing', to: 'boms#del_billing',via: 'get' 
  match '/del_shipping', to: 'boms#del_shipping',via: 'get' 
  match '/edit_shipping_js', to: 'boms#edit_shipping_js',via: 'post'
  match '/update_bom', to: 'boms#update_bom',via: 'post'
  match '/get_bom', to: 'boms#get_bom',via: 'get'
  match '/del_bom', to: 'boms#del_bom',via: 'post'
  match '/add_bom', to: 'boms#add_bom',via: 'post'

  resources :boms, only: [:index,:show, :new, :create, :destroy, :mark, :mpn]
  #resources :boms
  resources :bom_item
  #match '/search', to: 'boms#search', via: 'get'

  #match 'choose'=> 'boms#choose'
  match '/mark', to: 'boms#mark', via: 'post'
  match '/s_mpn', to: 'boms#s_mpn', via: 'post'
  match '/bom_item/add', to: 'bom_item#add', via: 'post'
  match '/root', to: 'boms#root', via: 'post'
  match '/upload', to: 'boms#upload', via: 'get'
  #
  match '/bom_item/select_with_ajax', to: 'bom_item#select_with_ajax', via: 'post'
  # The priority is based upon order of creation: first created -> highest priority.
  # See how all your routes lay out with "rake routes".

  # You can have the root of your site routed with "root"
  # root 'welcome#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end
