# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 702c941f35fc15b757020be640f0000ba53051b20202f790f57f40ac6c56f94230ed6ceba3c33c195f03410a2c08b858340909ce3d24ee523a1b1f8c27c17894

test:
  secret_key_base: 244f67451d34026601a3114213f3a90483f1ea07355564f5295ef8ef9ab4df65b663f38c37c13426c454d2b7e59ad909e77b325b7488f96c353ada112d885531

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 4aa8c0473dbdd734273dfbfc62ec6481ac844d3cd2fe6b32e6a1f5cbd49d6317af773e1d27e57e2a6facfb9c8768770073e686ad1fff33eb755bb61670901fb9
